<p>

<p style="text-align:center"><img src="/Ajax/Pictures/Analyse.JPG" /></p>

<p style="text-align:center"><a style="text-align:center;font-weight:bold;" href="/index.html">Retour au CV</a></p>

<ul type="square"><span style="font-weight:bold;">Caractéristiques :</span>
<li><span style="text-decoration:underline;">Type de compétence</span>: Analyse.</li>
<li><span style="text-decoration:underline;">Lieu d'exercice</span>: Secoia.</li>
<li><span style="text-decoration:underline;">Date d'exercice</span>: 2005-2009. </li>
<li><span style="text-decoration:underline;">Durée d'exercice</span>: 4 ans.</li>
<li><span style="text-decoration:underline;">Difficulté</span>: <img src="/Ajax/Pictures/Etoiles_4.JPG" /></li>
</ul>

<ul type="square"><span style="font-weight:bold;">Description de la mission :</span> 
<li>Création de schémas de synthèse Powerpoint illustrant des processus de calcul.</li>
</ul>

<ul type="square"><span style="font-weight:bold;">Utilité de la mission :</span>
<li>Synthétiser toute la logique de calcul d'une prestation dans un document unique.</li>
<li>Faciliter la compréhension du client de certains calculs complexes et élaborés.<li>
</ul>

<ul type="square"><span style="font-weight:bold;">Sous activités mobilisées :</span>
<li>Se documenter sur les conditions d'application d'une prestation sociale.</li>
<li>Modéliser la logique de calcul d'une prestation sociale.</li>
<li>Elaborer des schémas de synthèse détaillés sous Excel ou Power Point.</li>
<li>Créer des croquis synthétiques avec une touche esthétique agréable à l'oeil.</li>
</ul>

<ul type="square"><span style="font-weight:bold;">Qualités requises :</span>
<li>Créativité et imagination.</li>
<li>Esprit de synthèse.</li>
<li>Capacités d'abstraction.</li>
<li>Rigueur et minutie.</li>
<li>Soin du détail et de la précision.</li>
</ul>

<ul type="square"><span style="font-weight:bold;">Compétences nécessaires :</span>
<li>Maîtrise d'Excel et de Powerpoint.</li>
<li>Notions juridiques de droit social.</li>
<li>Culture graphique et sens de l'esthétique.</li>
<li>Esprit de pédagogie et de vulgarisation.</li>
<li>Aptitudes à créer des croquis synthétiques ayant un bon rendu visuel.</li>
</ul>

<p style="text-align:center"><a style="text-align:center;font-weight:bold;" href="/HTML/Secoia_SDS.html">Description plus détaillée.</a></p>

<p style="text-align:center"><img src="/Ajax/Pictures/Analyse.JPG" /></p>

</p>