CREATE FUNCTION F_TENLIGNE (@DD DATE, @DF DATE)
RETURNS TABLE
AS
RETURN (SELECT [PJR_DATE], PJS_ID
        FROM   [S_CLD].[T_PLN_JOUR_PJR]
        WHERE  [PJR_DATE] BETWEEN @DD AND @DF);
GO

CREATE FUNCTION F_TMULTIINST (@DD DATE, @DF DATE)
RETURNS @T TABLE (JOUR DATE, NUMJOUR TINYINT) 
AS
BEGIN
   WHILE @DD <= @DF
   BEGIN
      INSERT INTO @T SELECT @DD, DATEPART(weekday, @DD);
      SET @DD = DATEADD(day, 1, @DD);
   END;
   RETURN;
END;
GO

SET STATISTICS TIME ON

SELECT *
FROM   F_TENLIGNE ('2001-01-01' , '2029-12-31')
go

SELECT *
FROM   F_TMULTIINST ('2001-01-01' , '2029-12-31')
go





