  USE TECH;

  INSERT INTO [TECH].[dbo].[FRW_FLUX_DESCRIPTION]
	([CHAINE_NAME]
	,[FLUX_NAME]
    ,[JOB_NAME]
    ,[JOB_POSITION]
    ,[FLUX_CONSTRAINT])

	VALUES ('HENNECKE','DWH_PRO_LOG','JOB_DTM_PRO_LOGS_TRI',2,'ODS_PRO_LOG');

GO

