USE [master]  
GO  
EXEC master.dbo.sp_addlinkedserver   
    @server = N'SRV-SSIS-DWH\DWH_CELL',   
    @srvproduct=N'SQL Server' ;  
GO  

USE [SQC_DB];
CREATE SYNONYM [dbo].[VUE_MESURES_STATS_WAVESLABS] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VUE_MESURES_STATS_WAVESLABS]
-- SYNONYME : WAFER_WAV
CREATE SYNONYM [dbo].[WAFER_WAV] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[WAFER_WAV]
-- SYNONYME : RECIPE_WAV
CREATE SYNONYM [dbo].[RECIPE_WAV] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[RECIPE_WAV]
	

