forfiles /p "D:\SAS\Config\Lev1\Web\SASEnvironmentManager\server-5.8.0-EE\logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\SASEnvironmentManager\agent-5.8.0-EE\log" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer1_1\logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer2_1\logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer12_1\logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\WebServer\logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\Logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Applications\SASVisualAnalytics\VisualAnalyticsAdministrator\Logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Applications\SASVisualAnalytics\VisualAnalyticsAdministrator\VALIBLA\Logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Applications\SASVisualAnalytics\VisualAnalyticsAdministrator\EVDMLA\Logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "F:\SAS\Config\Lev1\Logs" /s /m *.* /c "cmd /c del @Path"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer1_1\temp" /s /m * /c "cmd /c del @Path /Q"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer2_1\temp" /s /m * /c "cmd /c del @Path /Q"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer12_1\temp" /s /m * /c "cmd /c del @Path /Q"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer1_1\work" /s /m * /c "cmd /c del @Path /Q"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer2_1\work" /s /m * /c "cmd /c del @Path /Q"
forfiles /p "D:\SAS\Config\Lev1\Web\WebAppServer\SASServer12_1\work" /s /m * /c "cmd /c del @Path /Q"