--DROP TABLE T_PRODUIT_PRD; 

CREATE TABLE T_PRODUIT_PRD
(PRD_ID     INT IDENTITY PRIMARY KEY)
GO

DROP TABLE T_PRODUIT_DESIGNATION;
DROP TABLE T_PRODUIT_PRIX;
DROP TABLE T_PRODUIT_TVA;

GO



CREATE TABLE T_PRODUIT_DESIGNATION
(PRD_ID     INT REFERENCES T_PRODUIT_PRD(PRD_ID),
 PRD_DESIGNATION    VARCHAR(30),
 PRD_DES DATE NOT NULL DEFAULT GETDATE(),
PRIMARY KEY (PRD_ID,PRD_DES));
GO

CREATE TABLE T_PRODUIT_PRIX
(PRD_ID     INT REFERENCES T_PRODUIT_PRD(PRD_ID),
 PRIX_HT DECIMAL(16,2) NOT NULL,
 PRD_DES DATE NOT NULL DEFAULT GETDATE(),
 PRIMARY KEY (PRD_ID,PRD_DES));
GO

CREATE TABLE T_PRODUIT_TVA
(PRD_ID     INT REFERENCES T_PRODUIT_PRD(PRD_ID),
 TAUX_TVA FLOAT NOT NULL,
 PRD_DES DATE NOT NULL DEFAULT GETDATE(),
 PRIMARY KEY (PRD_ID,PRD_DES));
GO

ALTER VIEW V_PRODUIT_DESIGNATION
AS 
SELECT PRD_ID,PRD_DESIGNATION,PRD_DES AS PRD_D_DEBUT,
	   COALESCE((SELECT DATEADD(day,-1,MIN(PRD_DES))
				FROM  T_PRODUIT_DESIGNATION AS TIN
				WHERE TIN.PRD_ID = TOUT.PRD_ID
				AND TIN.PRD_DES > TOUT.PRD_DES),'9999-12-31') AS PRD_DES_FIN
       FROM T_PRODUIT_DESIGNATION AS TOUT
GO

ALTER VIEW V_PRODUIT_PRIX
AS 
SELECT PRD_ID,PRIX_HT,PRD_DES AS PRD_PRX_DEBUT,
	   COALESCE((SELECT DATEADD(day,-1,MIN(PRD_DES))
				FROM  T_PRODUIT_PRIX AS TIN
				WHERE TIN.PRD_ID = TOUT.PRD_ID
				AND TIN.PRD_DES > TOUT.PRD_DES),'9999-12-31') AS PRD_PRX_FIN
       FROM T_PRODUIT_PRIX AS TOUT
GO
	
ALTER VIEW V_PRODUIT_TVA
AS 
SELECT PRD_ID,TAUX_TVA,PRD_DES AS PRD_TVA_DEBUT,
	   COALESCE((SELECT DATEADD(day,-1,MIN(PRD_DES))
				FROM  T_PRODUIT_TVA AS TIN
				WHERE TIN.PRD_ID = TOUT.PRD_ID
				AND TIN.PRD_DES > TOUT.PRD_DES),'9999-12-31') AS PRD_TVA_FIN
       FROM T_PRODUIT_TVA AS TOUT
GO

DECLARE @NEWID INT;
INSERT INTO dbo.T_PRODUIT_PRD DEFAULT VALUES;
SET @NEWID = SCOPE_IDENTITY();
INSERT INTO T_PRODUIT_PRIX VALUES(@NEWID,123.45,'2012-01-01');
INSERT INTO T_PRODUIT_DESIGNATION VALUES(@NEWID,'Pelle à gâteaux','2012-01-06');
INSERT INTO T_PRODUIT_TVA VALUES (@NEWID, 17.6, '2012-01-01');
INSERT INTO T_PRODUIT_PRIX VALUES (@NEWID, 125.00, '2014-07-01');
INSERT INTO T_PRODUIT_PRIX VALUES (@NEWID,130.00,'2014-09-01');
INSERT INTO T_PRODUIT_PRIX VALUES (@NEWID, 130.00, '2015-09-01');
INSERT INTO T_PRODUIT_TVA VALUES (@NEWID, 19.6, '2013-06-30');

SELECT * FROM V_PRODUIT_DESIGNATION;
SELECT * FROM V_PRODUIT_PRIX;
SELECT * FROM V_PRODUIT_TVA;
