-- créer une fonction qui nettoie les caractères autres que les chiffres et remplace le + par 00
ALTER FUNCTION F_CLEAN_TEL (@NUMERO VARCHAR(32))
RETURNS VARCHAR(32) 
WITH RETURNS NULL ON NULL INPUT
AS
BEGIN

IF @NUMERO = '' RETURN '';

SET @NUMERO = REPLACE(@NUMERO,'+','00');

DECLARE @I TINYINT = 1;
DECLARE @NewNumero VARCHAR(32) = '';
	
	WHILE @I <= LEN(@Numero)
		BEGIN
			SET @NewNumero = @NewNumero + 
					CASE 
						WHEN SUBSTRING(@NUMERO,@I,1) BETWEEN '0' AND '9' THEN SUBSTRING(@NUMERO,@I,1)		
						WHEN SUBSTRING(@NUMERO,@I,1) IN (' ') THEN ''
						ELSE ''
					END;
		SET @I=@I+1;
		END;
RETURN @NewNUMERO;
END
GO

SELECT dbo.F_CLEAN_TEL('+ 09 56e46466');

CREATE TABLE T_TEL
(TEL_ID     INT IDENTITY PRIMARY KEY,
 TEL_NUM    VARCHAR(30))
GO

-- créer le déclencheur
ALTER TRIGGER E_IU_TEL
ON T_TEL
FOR INSERT, UPDATE
AS
	SET NOCOUNT ON;
	UPDATE T_TEL 
		SET TEL_NUM = dbo.F_CLEAN_TEL(I.TEL_NUM)
		FROM T_TEL AS T INNER JOIN INSERTED AS I
		ON T.TEL_ID = I.TEL_ID
					
GO
DELETE FROM T_TEL;
-- test :
INSERT INTO T_TEL VALUES
('67.98.45.33.89'), ('+33 6 45 67 89 34'), ('06-56-34-23-12');

SELECT * FROM T_TEL;
