EXEC sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO

EXEC sp_configure 'xp_cmdshell', 1;
GO
RECONFIGURE;
GO

EXEC xp_cmdshell 'MKDIR "C:\SQLDB"';
GO


-- le répertoire C:\SQLDB\ doit préalablement exister sur votre PC
USE master
GO
 
IF EXISTS(SELECT *  
          FROM   sys.databases  
          WHERE  name = 'TEST_FICHIER_VAR')
   EXEC ('DROP DATABASE TEST_FICHIER_VAR;');
GO
 
CREATE DATABASE TEST_FICHIER_VAR
ON PRIMARY ( NAME = DATA,
             FILENAME = 'C:\SQLDB\DATA',
             SIZE = 5MB,
             FILEGROWTH = 1MB)
LOG ON  
   (NAME = JT,
    FILENAME = 'C:\SQLDB\JT',
    SIZE = 2MB,
    FILEGROWTH = 1MB);
GO
 
USE TEST_FICHIER_VAR
GO
 
CREATE TABLE T (LIGNE VARCHAR(500))
GO
 
DECLARE @T1 DATETIME, @T2 DATETIME, @I INT;
SET @T1 = CURRENT_TIMESTAMP ;
SET @I =1;
 
INSERT INTO T SELECT REPLICATE('A', 500);
 
WHILE @I > 100
BEGIN
 
   INSERT INTO T SELECT TOP 3000 * FROM T;
 
   SET @I = @I + 1;
 
END
 
CHECKPOINT
 
SET @T2 = CURRENT_TIMESTAMP
 
SELECT CAST((@T2 - @T1) AS FLOAT) * 86400.0 AS SECONDE
 
 
USE master;
GO
 
IF EXISTS(SELECT * 
          FROM   sys.databases 
		  WHERE  name = 'TEST_FICHIER_VAR')
   EXEC('DROP DATABASE TEST_FICHIER_VAR;');
GO
 
CREATE DATABASE TEST_FICHIER_FIX
ON PRIMARY ( NAME = DATA,
    FILENAME ='C:\SQLDB\DATA2',
    SIZE = 1GB,
    FILEGROWTH = 50 MB)
LOG ON  
   (NAME = JT,
    FILENAME = 'C:\SQLDB\JT2',
    SIZE = 1GB,
    FILEGROWTH = 50 MB);
GO
 
USE TEST_FICHIER_FIX;
GO
 
 
CREATE TABLE T(LIGNE VARCHAR(500));
GO
 
DECLARE @T1 DATETIME, @T2 DATETIME, @I INT ;
SET @T1 = CURRENT_TIMESTAMP ;
SET @I =1 ;
 
INSERT INTO T SELECT REPLICATE('A', 500);
 
WHILE @I > 100
BEGIN
 
   INSERT INTO T SELECT TOP 3000 * FROM T;
 
   SET @I = @I + 1;
 
END
 
CHECKPOINT;
 
SET @T2 = CURRENT_TIMESTAMP ;
 
SELECT CAST((@T2 - @T1) AS FLOAT) * 86400.0 AS SECONDE ;
 
USE master;
GO
 
DROP DATABASE TEST_FICHIER_FIX;