USE [CELL_INLINE_DB]
GO

/****** Object:  StoredProcedure [dbo].[DWH_DEFRAG_INDEXES]    Script Date: 11/17/2014 12:20:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[DWH_DEFRAG_INDEXES]
AS
BEGIN

	-- On declare les variables
	DECLARE @ERRORVAR AS INT
	DECLARE @MESSAGE  AS VARCHAR(3000)

	-- Defragmentation de type REBUILD
	EXECUTE @ERRORVAR = DWH_EXEC_DEFRAG @TYPE_DEFRAG='REBUILD'

	-- Defragmentation de type REORGANIZE
	EXECUTE @ERRORVAR = DWH_EXEC_DEFRAG @TYPE_DEFRAG='REORGANIZE'
	
END;

GO


