USE [master]
ALTER DATABASE [GMAO_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

RESTORE DATABASE [GMAO_DB] FROM  DISK = N'E:\MSSQL\MSSQL10_50.GMAO_REC\MSSQL\Backup\GMAO_DB_backup_2017_04_09_040003_4186863.bak' WITH  FILE = 1,  
	MOVE N'GMAO' TO N'E:\MSSQL\MSSQL10_50.GMAO_REC\MSSQL\Data\GMAO_REC_MDF\GMAO.mdf',  
	MOVE N'GMAO_log' TO N'E:\MSSQL\MSSQL10_50.GMAO_REC\MSSQL\Data\GMAO_REC_LDF\GMAO_log.ldf',  
	NOUNLOAD,  REPLACE,  STATS = 5

ALTER DATABASE [GMAO_DB] SET MULTI_USER

GO
