-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
--											CREATION DES SYNONYMES 
-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

/* Utilisation de la base SSIS_DB */
USE [SSIS_DB]
GO

-- -------------------------------------------------------------------------------------------------------------------------------
-- SUPPRESSION DES SYNONYMES
-- -------------------------------------------------------------------------------------------------------------------------------

-- ======================================================== EQUIPEMENT (ELOGIA) ==================================================

-- SYNONYME : TRI_CELLULE    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'TRI_CELLULE')
	DROP SYNONYM [dbo].[TRI_CELLULE]

-- SYNONYME : TRI_LOT    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'TRI_LOT')
	DROP SYNONYM [dbo].[TRI_LOT]

-- ======================================================== DATA WAREHOUSE =======================================================

-- SYNONYME : WAFER_WAV    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'WAFER_WAV')
	DROP SYNONYM [dbo].[WAFER_WAV]

-- SYNONYME : RECIPE_WAV    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'RECIPE_WAV')
	DROP SYNONYM [dbo].[RECIPE_WAV]

-- SYNONYME : WAFER_TRI    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'WAFER_TRI')
	DROP SYNONYM [dbo].[WAFER_TRI]

-- SYNONYME : WAFER_TRI_LOT    
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'WAFER_TRI_LOT')
	DROP SYNONYM [dbo].[WAFER_TRI_LOT]
	
-- SYNONYME : V_STATUT_WAFER_WAV
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'V_STATUT_WAFER_WAV')
	DROP SYNONYM [dbo].[V_STATUT_WAFER_WAV]
	
-- SYNONYME : VD_PRODUCTION_CLASSES
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES]

-- SYNONYME : VD_PRODUCTION_CLASSES_ELECTROLUM
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_ELECTROLUM')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_ELECTROLUM]

-- SYNONYME : VD_PRODUCTION_CLASSES_FLASHEUR
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_FLASHEUR')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_FLASHEUR]

-- SYNONYME : VD_PRODUCTION_CLASSES_INFRA_ROUGE
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_INFRA_ROUGE')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_INFRA_ROUGE]

-- SYNONYME : VD_PRODUCTION_CLASSES_VALIDES
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_VALIDES')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VALIDES]

-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_N
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_VISION_N')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_N]

-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_P
IF  EXISTS (SELECT * FROM sys.synonyms WHERE name = N'VD_PRODUCTION_CLASSES_VISION_P')
	DROP SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_P]
	
-- -------------------------------------------------------------------------------------------------------------------------------
-- RE-CREATION DES SYNONYMES
-- -------------------------------------------------------------------------------------------------------------------------------

-- ======================================================== EQUIPEMENT (ELOGIA) ==================================================

-- SYNONYME : TRI_CELLULE  
CREATE SYNONYM [dbo].[TRI_CELLULE] FOR [xx.xx.xx.xx].[Tri6].[dbo].[Cellule]
GO

-- SYNONYME : TRI_LOT  
CREATE SYNONYM [dbo].[TRI_LOT] FOR [xx.xx.xx.xx].[Tri6].[dbo].[Lot]
GO

-- ======================================================== DATA WAREHOUSE =======================================================

-- Recuperation du nom du service courant : IMPORT_DEV ou IMPORT_PROD
DECLARE @NOMSERVICE AS VARCHAR(50)
-- Initialisation des variables
SELECT @NOMSERVICE = @@SERVICENAME

-- ON SE TROUVE SUR LE DWH PRODUCTION
IF @NOMSERVICE = 'IMPORT_PROD'
	BEGIN 
		-- SYNONYME : WAFER_WAV
		CREATE SYNONYM [dbo].[WAFER_WAV] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[WAFER_WAV]
		-- SYNONYME : RECIPE_WAV
		CREATE SYNONYM [dbo].[RECIPE_WAV] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[RECIPE_WAV]
		-- SYNONYME : WAFER_TRI
		CREATE SYNONYM [dbo].[WAFER_TRI] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[WAFER_TRI]
		-- SYNONYME : WAFER_TRI_LOT
		CREATE SYNONYM [dbo].[WAFER_TRI_LOT] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[WAFER_TRI_LOT]
		-- SYNONYME : V_STATUT_WAFER_WAV
		CREATE SYNONYM [dbo].[V_STATUT_WAFER_WAV] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[V_STATUT_WAFER_WAV]
		-- SYNONYME : VD_PRODUCTION_CLASSES
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES]
		-- SYNONYME : VD_PRODUCTION_CLASSES_ELECTROLUM
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_ELECTROLUM] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_ELECTROLUM]
		-- SYNONYME : VD_PRODUCTION_CLASSES_FLASHEUR
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_FLASHEUR] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_FLASHEUR]
		-- SYNONYME : VD_PRODUCTION_CLASSES_INFRA_ROUGE
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_INFRA_ROUGE] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_INFRA_ROUGE]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VALIDES
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VALIDES] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VALIDES]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_N
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_N] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VISION_N]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_P
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_P] FOR [SRV-SSIS-DWH\DWH_CELL].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VISION_P]
	END
-- ON SE TROUVE SUR LE DWH DEVELOPPEMENT
ELSE IF @NOMSERVICE = 'IMPORT_DEV'
	BEGIN 
		-- SYNONYME : WAFER_WAV
		CREATE SYNONYM [dbo].[WAFER_WAV] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[WAFER_WAV]
		-- SYNONYME : RECIPE_WAV
		CREATE SYNONYM [dbo].[RECIPE_WAV] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[RECIPE_WAV]
		-- SYNONYME : WAFER_TRI
		CREATE SYNONYM [dbo].[WAFER_TRI] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[WAFER_TRI]
		-- SYNONYME : WAFER_TRI_LOT
		CREATE SYNONYM [dbo].[WAFER_TRI_LOT] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[WAFER_TRI_LOT]
		-- SYNONYME : V_STATUT_WAFER_WAV
		CREATE SYNONYM [dbo].[V_STATUT_WAFER_WAV] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[V_STATUT_WAFER_WAV]
		-- SYNONYME : VD_PRODUCTION_CLASSES
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES]
		-- SYNONYME : VD_PRODUCTION_CLASSES_ELECTROLUM
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_ELECTROLUM] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_ELECTROLUM]
		-- SYNONYME : VD_PRODUCTION_CLASSES_FLASHEUR
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_FLASHEUR] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_FLASHEUR]
		-- SYNONYME : VD_PRODUCTION_CLASSES_INFRA_ROUGE
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_INFRA_ROUGE] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_INFRA_ROUGE]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VALIDES
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VALIDES] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VALIDES]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_N
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_N] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VISION_N]
		-- SYNONYME : VD_PRODUCTION_CLASSES_VISION_P
		CREATE SYNONYM [dbo].[VD_PRODUCTION_CLASSES_VISION_P] FOR [SRV-SSIS-DEV\DWH_DEV].[CELL_INLINE_DB].[dbo].[VD_PRODUCTION_CLASSES_VISION_P]
	END
-- ON SE TROUVE AILLEURS
ELSE 
	PRINT 'SERVICE <' + @NOMSERVICE + '> NON PRIS EN COMPTE !!!'



